config/routes.rb
MemberManagement::Application.routes.draw do
  get 'login' => 'login#login'
  post 'login' => 'login#authenticate'
  get 'logout' => 'login#logout'
  get 'settings' => 'settings#settings'
  put 'settings' => 'settings#change_settings'
  get 'forgot' => 'login#forgot_password'
  post 'forgot' => 'login#new_password'

  resources :users
  resources :members

  root to: 'members#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_one :member

  scope :with_members, joins('LEFT JOIN members ON members.id = users.member_id')

  validates :email_address, uniqueness: true

  def self.search(search)
    if search
      if search.include? ';'
        search_params = search.split(pattern = ';')
        with_members.where("users.email_address like ? and
                           members.first_name like ? and
                           members.last_name like ? and
                           members.city like ? and
                           members.state like ? and
                           members.phone_number like ?",
                           parameterize(search_params[0]),
                           parameterize(search_params[1]),
                           parameterize(search_params[2]),
                           parameterize(search_params[3]),
                           parameterize(search_params[4]),
                           parameterize(search_params[5]))
      else
        with_members.where("users.email_address like :search or
                            members.first_name like :search or
                            members.last_name like :search or
                            members.city like :search or
                            members.state like :search or
                            members.phone_number like :search", { search: parameterize(search) })
      end
    else
      with_members
    end
  end

  def self.parameterize(parameter)
    parameter = '' if parameter.nil?
    '%' + parameter + '%'
  end

  def view_members_allowed?
    view_members
  end

  def edit_members_allowed?
    if APP_CONFIG[:allow_member_record_edits]
      edit_members
    else
      false
    end
  end

  def view_users_allowed?
    view_users
  end

  def edit_users_allowed?
    edit_users
  end
end

app/controllers/users_controller.rb
require 'securerandom'

class UsersController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :authenticate!
  before_action :redirect_if_view_users_not_allowed!
  before_action :redirect_if_edit_users_not_allowed!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    session[:users_sort] = params[:sort]
    session[:users_direction] = params[:direction]
    session[:users_page] = params[:page]
    session[:users_search] = params[:search]

    @users = User.search(session[:users_search]).order(sort_column + " " + sort_direction).paginate(per_page: 10, page: session[:users_page])
    set_tab(:users)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    set_tab(:users)
  end

  # GET /users/new
  def new
    @user = User.new
    set_tab(:users)
  end

  # GET /users/1/edit
  def edit
    set_tab(:users)
  end

  # POST /users
  # POST /users.json
  def create
    @password = SecureRandom.urlsafe_base64(8)
    @user = User.new( { 
      email_address: user_params[:email_address],
      password: @password,
      password_confirmation: @password,
      view_members: params[:view_members],
      edit_members: params[:edit_members],
      view_users: params[:view_users],
      edit_users: params[:edit_users]
    })

    respond_to do |format|
      if @user.save
        UserMailer.welcome_email(@user, @password).deliver
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update( { email_address: user_params[:email_address],
                        view_members: params[:view_members],
                        edit_members: params[:edit_members],
                        view_users: params[:view_users],
                        edit_users: params[:edit_users] })
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email_address, :password, :password_confirmation)
    end

    def sort_column
      if User.column_names.include?(session[:users_sort]) or Member.column_names.include?(session[:users_sort])
        session[:users_sort]
      else
        "email_address"
      end
    end
    
    def sort_direction
      %w[asc desc].include?(session[:users_direction]) ? session[:users_direction] : "asc"
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def display_permission(permission_field, permission_name)
    if permission_field
      (permission_name + "<br/>").html_safe
    end
  end

end

app/views/users/_form.html.haml
= form_for @user do |f|
  .container
    .row
      .col-md-8
        - if @user.errors.any?
          .alert.alert-danger
            %h6= pluralize(@user.errors.count, 'error') + ' prevented this user from being saved.'
            %ul
              - @user.errors.full_messages.each do |msg|
                %li.small= msg
    .row
      .col-md-3.form_group
        = f.label(:email_address, 'Email Address')
        = f.email_field(:email_address, :class => 'form-control', :autofocus => true)
      .col-md-4.col-md-offset-1
        = label_tag(:permissions, 'Permissions:')
        .checkbox
          = label_tag(:view_members) do
            = check_box_tag(:view_members, '1', @user.view_members)
            = 'View Members'
        .checkbox
          = label_tag(:edit_members) do
            = check_box_tag(:edit_members, '1', @user.edit_members)
            = 'Edit Members'
        .checkbox
          = label_tag(:view_users) do
            = check_box_tag(:view_users, '1', @user.view_users)
            = 'View Users'
        .checkbox
          = label_tag(:edit_users) do
            = check_box_tag(:edit_users, '1', @user.edit_users)
            = 'Edit Users'
    .row
      %div.col-md-8{ :style => 'text-align: right;' }
        = f.submit(nil, :class => 'btn btn-primary')
        = link_to(t('.cancel', :default => t("helpers.links.cancel")), users_path(:sort => session[:users_sort], :direction => session[:users_direction], :page => session[:users_page], :search => session[:users_search]), :class => 'btn btn-default')

app/views/users/edit.html.haml
- model_class = User
.container
  .row
    .col-md-8.col-md-offset-2
      %h3=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
      = render :partial => "form"

app/views/users/index.html.haml
- model_class = User
%h3=t '.title', :default => model_class.model_name.human.pluralize.titleize

= form_tag(users_path, method: 'get', :class => 'form-inline', :id => 'users_search') do
  .form-group
    = hidden_field_tag(:direction, params[:direction])
    = hidden_field_tag(:sort, params[:sort])
    = text_field_tag(:search, params[:search], :autofocus => true, :class => 'form-control input-sm')
    = submit_tag('Search', :class => 'btn btn-sm btn-default')
    = link_to('Clear', users_path, :class => 'btn btn-sm btn-default')

.table-responsive
  %table.table.table-hover.table-condensed
    %thead
      %tr
        %th
          = sortable_link 'email_address'
          %i{ :class => sortable_class('email_address') }
        %th
          = sortable_link 'first_name'
          %i{ :class => sortable_class('first_name') }
        %th
          = sortable_link 'last_name'
          %i{ :class => sortable_class('last_name') }
        %th
          = sortable_link 'city'
          %i{ :class => sortable_class('city') }
        %th
          = sortable_link 'state'
          %i{ :class => sortable_class('state') }
        %th
          = sortable_link 'phone_number'
          %i{ :class => sortable_class('phone_number') }
    %tbody
      - @users.each do |user|
        %tr{ :onclick => "location.href='#{user_path(user)}';", :style => 'cursor: pointer;' }
          %td= user.email_address
          %td= user.member.nil? ? '' : user.member.first_name
          %td= user.member.nil? ? '' : user.member.last_name
          %td= user.member.nil? ? '' : user.member.city
          %td= user.member.nil? ? '' : user.member.state
          %td= user.member.nil? ? '' : user.member.phone_number

= will_paginate @users
%br
- if User.find(session[:user]).edit_users_allowed?
  = link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.container
  .row
    .col-md-8.col-md-offset-2
      %h3=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
      = render :partial => "form"

app/views/users/settings.html.haml
.container
  .row
    .span8.offset2
      %h3= 'Settings'
      .row
        .span8
          - unless @errors.empty?
            .alert.alert-danger
              %h6= pluralize(@errors.count, 'error') + ' prevented these settings from being saved.'
              %ul
                - @errors.each do |msg|
                  %li= msg

      = form_tag('/change_settings', method: :put) do
        = hidden_field_tag(:authenticity_token, form_authenticity_token)
        .row
          .span4
            .form-group
              = label_tag(:email_address, 'Email Address')
              = email_field_tag(:email_address, @user.email_address, :class => 'form-control', :style => 'width: 100%;')
            .form-group
              = label_tag(:password, 'Password')
              = password_field_tag(:password, nil, :class => 'form-control', :style => 'width: 100%;')
            .form-group
              = label_tag(:password_confirmation, 'Confirm Password')
              = password_field_tag(:password_confirmation, nil, :class => 'form-control', :style => 'width: 100%;')
          .span4
            %h5= 'Associtated Member Record'
            - @members.each do |member|
              .form-group
                = label_tag(:member_record) do
                  = radio_button_tag(:member_record, member.id, member.id == @user.member_id, :onclick => "getMemberRecord(#{member.id});")
                  = "#{member.first_name} #{member.last_name}; #{member.email_address}; #{member.address1} #{member.address2}, #{member.city}, #{member.state}, #{member.zipcode}; #{member.phone_number}"
            .form-group
              = label_tag(:member_record) do
                = radio_button_tag(:member_record, '0', @user.member_id.nil?, :onclick => "clearMemberRecord();")
                = "None of the above"
        %br
        %br
        .row
          .span4.form-group
            = label_tag(:first_name, 'First Name')
            = text_field_tag(:first_name, nil, :class => 'form-control', :style => 'width: 100%;')
          .span4.form-group
            = label_tag(:last_name, 'Last Name')
            = text_field_tag(:last_name, nil, :class => 'form-control', :style => 'width: 100%;')
        .row
          .span4.form-group
            = label_tag(:phone_number, 'Phone Number')
            = telephone_field_tag(:phone_number, nil, :class => 'form-control', :style => 'width: 100%;')
        .row
          .span8.form-group
            = label_tag(:address1, 'Address 1')
            = text_field_tag(:address1, nil, :class => 'form-control', :style => 'width: 100%;')
        .row
          .span8.form-group
            = label_tag(:address2, 'Address 2')
            = text_field_tag(:address2, nil, :class => 'form-control', :style => 'width: 100%;')
        .row
          .span4.form-group
            = label_tag(:city, 'City')
            = text_field_tag(:city, nil, :class => 'form-control', :style => 'width: 100%;')
          .span1.form-group
            = label_tag(:state, 'State')
            = select_tag(:state, options_from_collection_for_select(us_states, :abbr, :abbr), { :class => 'form-control', :style => 'width: 100%; min-width: 60px;' })
          .span3.form-group
            = label_tag(:zipcode, 'Zipcode')
            = text_field_tag(:zipcode, nil, :class => 'form-control', :style => 'width: 100%;')
        .row
          %div{ :class => 'span8', :style => 'text-align: right;' }
            = submit_tag('Save', :class => 'btn btn-primary')
            = link_to(t('.cancel', :default => t("helpers.links.cancel")), members_path(:sort => session[:members_sort], :direction => session[:members_direction], :page => session[:members_page], :search => session[:members_search]), :class => 'btn')
:javascript
  $(document).ready(
    getMemberRecord($('input[name=member_record] :checked').val())
  );

app/views/users/show.html.haml
- model_class = User
.container
  .row
    .col-md-8.col-md-offset-2
      %h3=t '.title', :default => model_class.model_name.human.titleize
      .row
        .col-md-6
          =display_field(@user.email_address, 'Email Address')
        .col-md-6
          %strong= 'Permissions:'
          %br
          = display_permission(@user.view_members_allowed?, 'View Members')
          = display_permission(@user.edit_members_allowed?, 'Edit Members')
          = display_permission(@user.view_users_allowed?, 'View Users')
          = display_permission(@user.edit_users_allowed?, 'Edit Users')


      .row
        %br
        %div{ :style => 'text-align: right;' }
          = link_to t('.back', :default => t("helpers.links.back")), users_path(:sort => session[:users_sort], :direction => session[:users_direction], :page => session[:users_page], :search => session[:users_search]), :class => 'btn btn-default'
          - if User.find(session[:user]).edit_users_allowed?
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'