config/routes.rb
MemberManagement::Application.routes.draw do
  get 'login' => 'login#login'
  post 'login' => 'login#authenticate'
  get 'logout' => 'login#logout'
  get 'settings' => 'settings#settings'
  put 'settings' => 'settings#change_settings'
  get 'forgot' => 'login#forgot_password'
  post 'forgot' => 'login#new_password'

  resources :users
  resources :members

  root to: 'members#index'

end

app/controllers/login_controller.rb
require 'securerandom'

class LoginController < ApplicationController
  # GET /login
  def login
    set_tab(:login)
  end

  # POST /login
  def authenticate
    @user = User.where(email_address: params[:email_address]).first.try(:authenticate, params[:password])
    if @user
      session[:user] = @user.id
      cookies.signed[:user] = session[:user] unless params[:remember_me] != '1'
      if @user.member.nil?
        redirect_to settings_path
      else
        redirect_to members_path
      end
    else
      session[:user] = nil
      @error = 'Incorrect email address or password.'
      render action: 'login'
    end
    set_tab(:login)
  end

  # GET /logout
  def logout
    cookies.delete :user
    reset_session
    redirect_to login_path
  end

  # GET /forgot
  def forgot_password
    set_tab(:login)
  end

  # POST /forgot
  def new_password
    @user = User.where(email_address: params[:email_address]).first
    if @user
      @password = SecureRandom.urlsafe_base64(8)
      if @user.update( { password: @password, password_confirmation: @password })
        UserMailer.forgot_password_email(@user, @password).deliver
        @success = 'A new password has been emailed to you.'
      else
        @error = 'Unable to reset password at this time.'
      end
      render action: 'login'
    else
      @error = 'Email address not found.'
      render action: 'login'
    end
    set_tab(:login)
  end

end

app/views/login/forgot_password.html.haml
.container
  .row
    .col-md-4.col-md-offset-4
      %h3= 'Forgot Password'
      - if !@error.nil?
        .alert.alert-danger
          %small= @error
      - if !@success.nil?
        .alert.alert-success
          %small= @success
  .row
    .col-md-4.col-md-offset-4
      .jumbotron
        = form_tag(forgot_path, :method => 'post', :id => 'forgot_password_form') do
          .form-group
            = label_tag(:email_address, 'Email Address', :style => 'width: 100%;')
            = text_field_tag(:email_address, '', :class => 'form-control', :style => 'width: 100%;', :autofocus => true)
          .form-group
            = submit_tag('Submit', :class => 'btn btn-default pull-right')

app/views/login/login.html.haml
.container
  .row
    .col-md-4.col-md-offset-4
      %h3= 'Login'
      - if !@error.nil?
        .alert.alert-danger
          %small= @error
      - if !@success.nil?
        .alert.alert-success
          %small= @success
  .row
    .col-md-4.col-md-offset-4
      .jumbotron
        = form_tag(login_path, :method => 'post', :id => 'login_form') do
          .form-group
            = label_tag(:email_address, 'Email Address', :style => 'width: 100%;')
            = text_field_tag(:email_address, '', :class => 'form-control', :style => 'width: 100%;', :autofocus => true)
          .form-group
            = label_tag(:password, 'Password', :style => 'width: 100%;')
            = password_field_tag(:password, '', :class => 'form-control', :style => 'width: 100%;')
          .form-group
            = label_tag(:remember_me) do
              = check_box_tag(:remember_me)
              = 'Remember me?'
          .form-group
            = submit_tag('Login', :class => 'btn btn-default pull-right')
        %br
        %small
          = link_to('Forgot password?', forgot_path)