config/routes.rb
MemberManagement::Application.routes.draw do
  get 'login' => 'login#login'
  post 'login' => 'login#authenticate'
  get 'logout' => 'login#logout'
  get 'settings' => 'settings#settings'
  put 'settings' => 'settings#change_settings'
  get 'forgot' => 'login#forgot_password'
  post 'forgot' => 'login#new_password'

  resources :users
  resources :members

  root to: 'members#index'

end

app/views/layouts/application.html.haml
%html
  %head
    %title= "Jim's App - Members"
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{ :name => 'viewport', :content => 'width=device-width, initial-scale=1.0' }
  
  %body
    %div{ :class => 'navbar navbar-default navbar-fixed-top' }
      .navbar-inner
        .container
          %button{ :type => 'button', :class => 'navbar-toggle', 'data-toggle' => 'collapse', 'data-target' => '#main-nav-bar' }
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a{ :class => 'navbar-brand', :href => '#' }= "Jim's App - Members"

          - if session[:tab] != :login and session[:tab] != :sign_up and session[:tab] != nil
            #main-nav-bar.collapse.navbar-collapse
              %ul{ :class => 'nav navbar-nav' }
                - if User.find(session[:user]).view_members_allowed?
                  = content_tag(:li, link_to('Members', members_path), :class => "#{'active' if session[:tab] == :members}")
                - if User.find(session[:user]).view_users_allowed?
                  = content_tag(:li, link_to('Users', users_path), :class => "#{'active' if session[:tab] == :users}")

              %ul{ :class => 'nav navbar-nav navbar-right' }
                = content_tag(:li, link_to('Settings', settings_path), :class => "#{'active' if session[:tab] == :settings}")
                %li= link_to("Logout", logout_path)

    .container
      .row
        .span12= yield