config/routes.rb
MemberManagement::Application.routes.draw do
  get 'login' => 'login#login'
  post 'login' => 'login#authenticate'
  get 'logout' => 'login#logout'
  get 'settings' => 'settings#settings'
  put 'settings' => 'settings#change_settings'
  get 'forgot' => 'login#forgot_password'
  post 'forgot' => 'login#new_password'

  resources :users
  resources :members

  root to: 'members#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
  has_one :user

  def self.search(search)
    if search
      if search.include? ';'
        search_params = search.split(pattern = ';')
        where("first_name like ? and
               last_name like ? and
               email_address like ? and
               address1 like ? and
               city like ? and
               state like ? and
               zipcode like ? and
               phone_number like ?",
               parameterize(search_params[0]),
               parameterize(search_params[1]),
               parameterize(search_params[2]),
               parameterize(search_params[3]),
               parameterize(search_params[4]),
               parameterize(search_params[5]),
               parameterize(search_params[6]),
               parameterize(search_params[7]))
      else
        where("first_name like :search or
               last_name like :search or
               email_address like :search or
               phone_number like :search or
               address1 like :search or
               city like :search or
               state like :search or
               zipcode like :search", { search: parameterize(search) })
      end
    else
      scoped
    end
  end

  def self.parameterize(parameter)
    parameter = '' if parameter.nil?
    '%' + parameter + '%'
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :authenticate!
  before_action :redirect_if_view_members_not_allowed!, except: [:show]
  before_action :redirect_if_edit_members_not_allowed!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    session[:members_sort] = params[:sort]
    session[:members_direction] = params[:direction]
    session[:members_page] = params[:page]
    session[:members_search] = params[:search]

    @members = Member.search(session[:members_search]).order(sort_column + " " + sort_direction).paginate(per_page: 10, page: session[:members_page])
    set_tab(:members)
  end

  # GET /members/1
  # GET /members/1.json
  def show
    set_tab(:members)
  end

  # GET /members/new
  def new
    @member = Member.new
    set_tab(:members)
  end

  # GET /members/1/edit
  def edit
    set_tab(:members)
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render action: 'show', status: :created, location: @member }
      else
        format.html { render action: 'new' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:email_address, :first_name, :last_name, :address1, :address2, :city, :state, :zipcode, :phone_number)
    end

    def sort_column
      Member.column_names.include?(session[:members_sort]) ? session[:members_sort] : "first_name"
    end
    
    def sort_direction
      %w[asc desc].include?(session[:members_direction]) ? session[:members_direction] : "asc"
    end
end

app/helpers/members_helper.rb
module MembersHelper

  def us_states
    array = []
    array.push(State.new('AL', 'Alabama'))
    array.push(State.new('AK', 'Alaska'))
    array.push(State.new('AZ', 'Arizona'))
    array.push(State.new('AR', 'Arkansas'))
    array.push(State.new('CA', 'California'))
    array.push(State.new('CO', 'Colorado'))
    array.push(State.new('CT', 'Connecticut'))
    array.push(State.new('DE', 'Delaware'))
    array.push(State.new('DC', 'District of Columbia'))
    array.push(State.new('FL', 'Florida'))
    array.push(State.new('GA', 'Georgia'))
    array.push(State.new('HI', 'Hawaii'))
    array.push(State.new('ID', 'Idaho'))
    array.push(State.new('IL', 'Illinois'))
    array.push(State.new('IN', 'Indiana'))
    array.push(State.new('IA', 'Iowa'))
    array.push(State.new('KS', 'Kansas'))
    array.push(State.new('KY', 'Kentucky'))
    array.push(State.new('LA', 'Louisiana'))
    array.push(State.new('ME', 'Maine'))
    array.push(State.new('MD', 'Maryland'))
    array.push(State.new('MA', 'Massachusetts'))
    array.push(State.new('MI', 'Michigan'))
    array.push(State.new('MN', 'Minnesota'))
    array.push(State.new('MS', 'Mississippi'))
    array.push(State.new('MO', 'Missouri'))
    array.push(State.new('MT', 'Montana'))
    array.push(State.new('NE', 'Nebraska'))
    array.push(State.new('NV', 'Nevada'))
    array.push(State.new('NH', 'New Hampshire'))
    array.push(State.new('NJ', 'New Jersey'))
    array.push(State.new('NM', 'New Mexico'))
    array.push(State.new('NY', 'New York'))
    array.push(State.new('NC', 'North Carolina'))
    array.push(State.new('ND', 'North Dakota'))
    array.push(State.new('OH', 'Ohio'))
    array.push(State.new('OK', 'Oklahoma'))
    array.push(State.new('OR', 'Oregon'))
    array.push(State.new('PA', 'Pennsylvania'))
    array.push(State.new('RI', 'Rhode Island'))
    array.push(State.new('SC', 'South Carolina'))
    array.push(State.new('SD', 'South Dakota'))
    array.push(State.new('TN', 'Tennessee'))
    array.push(State.new('TX', 'Texas'))
    array.push(State.new('UT', 'Utah'))
    array.push(State.new('VT', 'Vermont'))
    array.push(State.new('VA', 'Virgina'))
    array.push(State.new('WA', 'Washington'))
    array.push(State.new('WV', 'West Virginia'))
    array.push(State.new('WI', 'Wisconsin'))
    array.push(State.new('WY', 'Wyoming'))
    return array
  end


  class State
    attr_accessor :abbr, :name

    def initialize(abbr, name)
      @abbr = abbr
      @name = name
    end
  end

end

app/views/members/_form.html.haml
= form_for @member do |f|
  .container
    .row
      .col-md-8
        - if @member.errors.any?
          .alert.alert-danger
            %h6= pluralize(@member.errors.count, 'error') + ' prevented this user from being saved.'
            %ul
              - @member.errors.full_messages.each do |msg|
                %li.small= msg
    .row
      .col-md-4.form-group
        = f.label(:first_name, 'First Name', :style => 'width: 100%;')
        = f.text_field(:first_name, :class => 'form-control', :style => 'width: 100%;', :autofocus => true)
      .col-md-4.form-group
        = f.label(:last_name, 'Last Name', :style => 'width: 100%;')
        = f.text_field(:last_name, :class => 'form-control', :style => 'width: 100%;')
    .row
      .col-md-4.form-group
        = f.label(:email_address, 'Email Address', :style => 'width: 100%;')
        = f.email_field(:email_address, :class => 'form-control', :style => 'width: 100%;')
      .col-md-4.form-group
        = f.label(:phone_number, 'Phone Number', :style => 'width: 100%;')
        = f.telephone_field(:phone_number, :class => 'form-control', :style => 'width: 100%;')
    .row
      .col-md-8.form-group
        = f.label(:address1, 'Address 1', :style => 'width: 100%;')
        = f.text_field(:address1, :class => 'form-control', :style => 'width: 100%;')
    .row
      .col-md-8.form-group
        = f.label(:address2, 'Address 2', :style => 'width: 100%;')
        = f.text_field(:address2, :class => 'form-control', :style => 'width: 100%;')
    .row
      .col-md-4.form-group
        = f.label(:city, :style => 'width: 100%;')
        = f.text_field(:city, :class => 'form-control', :style => 'width: 100%;')
      .col-md-1.form-group
        = f.label(:state, :style => 'width: 100%;')
        = f.collection_select(:state, us_states, :abbr, :abbr, {}, { :class => 'form-control', :style => 'width: 100%; min-width: 60px;' })
      .col-md-3.form-group
        = f.label(:zipcode, :style => 'width: 100%;')
        = f.text_field(:zipcode, :class => 'form-control', :style => 'width: 100%;')
    .row
      %div{ :class => 'col-md-8', :style => 'text-align: right;' }
        = f.submit(nil, :class => 'btn btn-primary')
        = link_to(t('.cancel', :default => t("helpers.links.cancel")), members_path(:sort => session[:members_sort], :direction => session[:members_direction], :page => session[:members_page], :search => session[:members_search]), :class => 'btn btn-default')

app/views/members/edit.html.haml
- model_class = Member
.container
  .row
    .col-md-8.col-md-offset-2
      %h3=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
      = render :partial => "form"

app/views/members/index.html.haml
- model_class = Member
%h3=t '.title', :default => model_class.model_name.human.pluralize.titleize

= form_tag(members_path, method: 'get', :class => 'form-inline', :id => 'members_search') do
  .form-group
    = hidden_field_tag(:direction, params[:direction])
    = hidden_field_tag(:sort, params[:sort])
    = text_field_tag(:search, params[:search], :autofocus => true, :class => 'form-control input-sm')
    = submit_tag('Search', :class => 'btn btn-sm btn-default')
    = link_to('Clear', members_path, :class => 'btn btn-sm btn-default')

.table-responsive
  %table.table.table-hover.table-condensed
    %thead
      %tr
        %th
          = sortable_link 'first_name'
          %i{ :class => sortable_class('first_name') }
        %th
          = sortable_link 'last_name'
          %i{ :class => sortable_class('last_name') }
        %th
          = sortable_link 'email_address'
          %i{ :class => sortable_class('email_address') }
        %th
          = sortable_link 'address1', 'Address'
          %i{ :class => sortable_class('address1') }
        %th
          = sortable_link 'city'
          %i{ :class => sortable_class('city') }
        %th
          = sortable_link 'state'
          %i{ :class => sortable_class('state') }
        %th
          = sortable_link 'zipcode'
          %i{ :class => sortable_class('zipcode') }
        %th
          = sortable_link 'phone_number'
          %i{ :class => sortable_class('phone_number') }
    %tbody
      - @members.each do |member|
        %tr{ :onclick => "location.href='#{member_path(member)}';", :style => 'cursor: pointer;' }
          %td= member.first_name
          %td= member.last_name
          %td= member.email_address
          %td= member.address1
          %td= member.city
          %td= member.state
          %td= member.zipcode
          %td= member.phone_number

= will_paginate @members
%br
- if User.find(session[:user]).edit_members_allowed?
  = link_to t('.new', :default => t("helpers.links.new")), new_member_path, :class => 'btn btn-primary'

app/views/members/new.html.haml
- model_class = Member
.container
  .row
    .col-md-8.col-md-offset-2
      %h3=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
      = render :partial => "form"

app/views/members/show.html.haml
- model_class = Member
.container
  .row
    .col-md-8.col-md-offset-2
      %h3=t '.title', :default => model_class.model_name.human.titleize
      .row
        .col-md-6
          = display_field(@member.first_name, 'First Name')
        .col-md-6
          = display_field(@member.last_name, 'Last Name')
      .row
        .col-md-6
          = display_email(@member.email_address, 'Email Address')
        .col-md-6
          = display_phone(@member.phone_number, 'Phone Number')
      .row
        .col-md-12
          = display_field(@member.address1, 'Address 1')
      .row
        .col-md-12
          = display_field(@member.address2.blank? ? '&nbsp;' : @member.address2, 'Address 2')
      .row
        .col-md-6
          = display_field(@member.city, 'City')
        .col-md-2
          = display_field(@member.state, 'State')
        .col-md-4
          = display_field(@member.zipcode, 'Zipcode')
      

      .row
        %br
        %div{ :class => 'span7', :style => 'text-align: right;' }
          = link_to t('.back', :default => t("helpers.links.back")), members_path(:sort => session[:members_sort], :direction => session[:members_direction], :page => session[:members_page], :search => session[:members_search]), :class => 'btn btn-default'
          - if User.find(session[:user]).edit_members_allowed?
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_member_path(@member), :class => 'btn btn-default'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), member_path(@member), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'